### PR TITLE
fix: Exclude collection-for from the warning of avoid_single_child

### LINKED ISSUE #42: Exclude cases with for-loops in ListLiterals from `avoid_single_child` warnings
The `avoid_single_child` rule should exclude cases where a `for` loop is used within a `ListLiteral`. For instance, the following usage of a `for` loop within the `children` property of a `Column` should not trigger the warning:

```dart
Column(
  children: [
    for (var i = 0; i < 10; i++) Text('Hello $i'),
  ],
),
```

This change ensures that dynamically generated lists using loops are not unnecessarily flagged by the rule.

- for
- if

### LINKED ISSUE #51: Question: Is `avoid_single_child` rule producing a false positive for collection for-loops?
I've been using the altive_lints package with `all_lint_rules.yaml` and recently started using the altive recommended rules. Thank you for this great package!

I've noticed that the `avoid_single_child` rule seems to flag a warning for `ListView` `children` when using a collection for-loop. I'd like to ask your opinion on whether this is intended behavior or a potential false positive.

Here's an example that triggers the lint:

```dart
ListView(
  children: [
    for (final todo in todos)
      ListTile(title: Text(todo.title)),
  ],
),
```

My understanding is that a collection for-loop can potentially generate multiple children, so this might not be a case where we're actually using a single child.

What are your thoughts on this? Do you consider this a false positive, or is there a reason for this behavior that I'm missing?

Environment:
- altive_lints version: 1.11.1
- Dart version: 3.4.3
- Flutter version: 3.22.2

Thank you for your time and consideration!

### PR DESCRIPTION
**Pull request by riscait**
## 🔗 Related Issues

- closes #42
- closes #51

## 🙌 What's Done

- Exclude collection-for from the warning of avoid_single_child

## ✍️ What's Not Done

- Exclude collection-if from the warning of avoid_single_child

## 🤼 Desired Review Method

- [ ] Correction Commit
- [ ] Pair programming

> [!NOTE]
> It is possible that a reviewer's will may cause a method to be implemented that is not selected.

## Pre-launch Checklist
- [x] I have reviewed my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I updated/added relevant documentation (doc comments with ///).

### CODE REVIEW

File: packages/altive_lints/lint_test/lints/avoid_single_child.dart [hunk 1]
```diff
@@ -44,12 +47,34 @@ class MyWidget extends StatelessWidget {
             Text('World'),
           ],
         ),
+        // expect_lint: avoid_single_child
+        Column(
+          children: [
+            if (random.nextBool()) const Text('Hello World'),
+          ],
+        ),
```
Comment (riscait) [inline packages/altive_lints/lint_test/lints/avoid_single_child.dart:55]: If a single element is enclosed in a collection-if, it will issue a warning even if it is enclosed in a collection-if.
There is no use for this; can we `ignore` it if there is?

Comment (naipaka) [reply packages/altive_lints/lint_test/lints/avoid_single_child.dart:55]: Yes, I agree.

File: packages/altive_lints/lib/src/lints/avoid_single_child.dart [hunk 2]
```diff
@@ -64,15 +64,23 @@ class AvoidSingleChild extends DartLintRule {
...
+          return;
+        }
+
+        if (childrenList.elements.length > 1) {
+          return;
+        }
 
-        if (childrenList != null && childrenList.elements.length == 1) {
-          reporter.atNode(node, _code);
+        final element = childrenList.elements.first;
```
Comment (naipaka) [inline packages/altive_lints/lib/src/lints/avoid_single_child.dart:79]: badge 
If `childrenList.elements` is empty, it seems like an error could occur here, but is it unlikely that this situation would happen?

To be safe, I considered options like issuing a warning only if there is only one element or using `firstOrNull`, but if it is indeed impossible for it to be empty, then leaving it as is should be fine.

**Review by naipaka — APPROVED** [review]
LGTM

File: packages/altive_lints/lib/src/lints/avoid_single_child.dart (hunk 2 above)
Comment (riscait) [reply packages/altive_lints/lib/src/lints/avoid_single_child.dart:79]: `const Column(),` did not cause an error.
`Column(children: [])` would have caused an error, but I couldn't write it because `avoid_redundant_argument_values` is in effect.

I added `isEmpty` handling in this commit (https://github.com/altive/altive_lints/pull/52/commits/1d9e36c54e9ba47cc54b525b88ad63797b382e64) just in case!
