### PR TITLE
fix: No warnings in test directory

### LINKED ISSUE #65: Exclude `avoid_hardcoded_japanese` for entire test directory, not just `*_test.dart`
I want to exclude `avoid_hardcoded_japanese` from test code.
Currently exclude only `*_test.dart`, but I want to exclude all test files such as test_utils.dart.

### PR DESCRIPTION
**Pull request by boywithdv**
## 🔗 Related Issues

- closes #65 

## 🙌 What's Done

- Do not display warnings in the test directory
- Removed the code that said to exclude warnings in _test.dart that was previously there.

## ✍️ What's Not Done

- 

## 🖼️ Image Differences

| Before    | After     |
| --------- | --------- |
| __image__ | __image__ |

## 🤼 Desired Review Method

- [ ] Correction Commit
- [ ] Pair programming

> [!NOTE]
> It is possible that a reviewer's will may cause a method to be implemented that is not selected.

## Pre-launch Checklist
- [ ] I have reviewed my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I updated/added relevant documentation (doc comments with ///).

### CODE REVIEW

File: packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart [hunk 1]
```diff
@@ -1,7 +1,6 @@
 // Check the `avoid_hardcoded_japanese` rule.
 //
-// This file ends with the name `_test.dart`,
-// so it should be exempt from the warning.
+// It should exclude warnings for the entire `/test/` directory.
```
Comment (riscait) [inline packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: badge
This file is not in the `/test/` directory.
I think you need to create a `/test/` directory and try it.

File: packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart [hunk 2]
```diff
@@ -40,6 +40,12 @@ class AvoidHardcodedJapanese extends DartLintRule {
     ErrorReporter reporter,
     CustomLintContext context,
   ) {
+    if (resolver.source.uri.toString().contains('/test/')) {
+      return;
+    }
+    // Although redundant, _test.dart is temporarily excluded here
+    // because the warning message appears in the _test.dart file
+    // in the lint_test directory.
```
Comment (riscait) [inline packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: badge
It is not necessary to write in the product code of the test thing.
Please respond to changes in requirements in the product code on the load and test side.

**Review by riscait — CHANGES_REQUESTED** [review]

File: packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart (hunk 1 above)
Comment (boywithdv) [reply packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: Since the `/test/` directory does not currently exist, I would like to create a `/test/` directory and deal with it there.

I would like to create the `/test/` directory on top of `/lint_test/`.

File: packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart (hunk 2 above)
Comment (boywithdv) [reply packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: Indeed, the logic targeting test code and test directories seems unnecessary, so we will remove this one.

Comment (riscait) [reply packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: It would be better to leave the '_test.dart' decision in place for backward compatibility, just in case.

File: packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart (hunk 1 above)
Comment (boywithdv) [reply packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: Instead of creating a `/test/` directory on top of the `/lint_test/` directory, the name was changed from `/lint_test/`  to `/test/`.

The reason is that it feels strange to have a `/lint_test/` directory inside a `/test/` directory, and it seems better to just keep it short and simple as test directory.

Change : https://github.com/altive/altive_lints/pull/70/commits/62d3bcdc710ed810e1145d92a1dfce16c6676c07

File: packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart (hunk 2 above)
Comment (boywithdv) [reply packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: Thank you very much.

In the meantime, I have taken the form of leaving `_test.dart` and deleted the unnecessary comment content.

Change : https://github.com/altive/altive_lints/pull/70/commits/5f6dc0bc3337e5f654fe23b63672637017578058

File: packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart (hunk 1 above)
Comment (riscait) [reply packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: @naipaka 
He has renamed the common `lint_test` directory to the `test` directory, is this ok?
I thought I should only add the `test` directory for rules that I want to test in the `test` directory, but if renaming all `lint_test` to `test` is ok, then maybe this is ok too🤔

File: packages/altive_lints/test/lints/avoid_hardcoded_japanese.dart [hunk 3]
```diff
@@ -1,12 +1,9 @@
 // Check the `avoid_hardcoded_japanese` rule.
 
-// expect_lint: avoid_hardcoded_japanese
```
Comment (riscait) [inline packages/altive_lints/test/lints/avoid_hardcoded_japanese.dart]: badge
Why did you remove `expect_lint`?

File: packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart [hunk 4]
```diff
@@ -40,6 +40,9 @@ class AvoidHardcodedJapanese extends DartLintRule {
     ErrorReporter reporter,
     CustomLintContext context,
   ) {
+    if (resolver.source.uri.toString().contains('/test/')) {
```
Comment (riscait) [inline packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: badge
`toString()` is hacky. Could `uri.pathSegments` be used?

Comment (boywithdv) [reply packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: pathSegments looks good for structural processing such as checking paths and segments.

We will change from toString() to pathSegments.

File: packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart (hunk 1 above)
Comment (naipaka) [reply packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: In my understanding, there is an issue.

The Dart test framework usually requires a `main` function. 
However, for lint rule testing, the `main` function is not utilized, which is why I created a separate `lint_test` directory instead of using `test`. 
(At the time, I believe an error indicating that a main entry point could not be found when running `flutter test` was occurring…)

In the latest commit, `pubspec.yaml` and `analysis_options.yaml` are located within the `test` directory, which also seems unusual.

---

The name `lint_test` might have been misleading. 
Looking at other repositories that use custom_lint for lint packages, it seems that some check for lints within the `example` directory using `expect_lint: xxx`. 
Therefore, the following directory structure might be a suitable alternative:

```
altive_lints/
├── lib/
├── example/
│   └── main.dart
│   └── lints
│       └── avoid_consecutive_sliver_to_box_adapter.dart
│   └── test
│       └── xxx.dart
└── pubspec.yaml
```

Comment (riscait) [reply packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: @naipaka 
Thanks for the details!

@boywithdv 
I have a problem with the `test` directory, so please change it to the above configuration.

File: packages/altive_lints/test/lints/avoid_hardcoded_japanese.dart (hunk 3 above)
Comment (boywithdv) [reply packages/altive_lints/test/lints/avoid_hardcoded_japanese.dart]: The change from lint_test to test has been made so that contents in the test directory cannot warn.
This section was also removed because it is no longer possible to warn.

File: packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart (hunk 1 above)
Comment (boywithdv) [reply packages/altive_lints/lint_test/lints/avoid_hardcoded_japanese_test.dart]: @naipaka 
Thank you for the detailed explanation!

@riscait 
> I have a problem with the test directory, so please change it to the above configuration.

Yes, sir.
We will make the correction again, and if it looks OK, we will submit another review request.

**Comment by boywithdv** [comment]
@riscait 

Correction and self review completed.
The following actions have been taken

- `/example/analysis_options.yaml`, set the rule for avoid_hardcoded_color to true
- Avoid warnings in `/test/ directory`
- Move the contents of `/lint_test/lints to example/lints/`
- Create `example/test/` directory

File: packages/altive_lints/example/test/avoid_hardcoded_japanese_test.dart [hunk 5]
```diff
@@ -0,0 +1,9 @@
+// Check the `avoid_hardcoded_japanese` rule.
+//
+// It should exclude warnings for the entire `/test/` directory.
```
Comment (riscait) [inline packages/altive_lints/example/test/avoid_hardcoded_japanese_test.dart]: badge
It is not necessary to enclose the directory with `/` since it is specified as a “directory”.　

```suggestion
// It should exclude warnings for the entire `test` directory.
```

File: packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart [hunk 6]
```diff
@@ -40,6 +40,9 @@ class AvoidHardcodedJapanese extends DartLintRule {
     ErrorReporter reporter,
     CustomLintContext context,
   ) {
+    if (resolver.source.uri.pathSegments.contains('/test/')) {
+      return;
+    }
```
Comment (riscait) [inline packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: badge
From reading the documentation, isn't `/` unnecessary?
Read the documentation comments when implementing.

**Review by riscait — APPROVED** [review]
LGTM
Thanks! Only minor points were commented on!

File: packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart (hunk 6 above)
Comment (boywithdv) [reply packages/altive_lints/lib/src/lints/avoid_hardcoded_japanese.dart]: It seems unnecessary since pathSegments are stored in a list with each slash.
We will remove the slashes in an additional commit.
