### PR TITLE
fix: Add stack to avoid_single_child

### LINKED ISSUE #45: Add Stack to the avoid_single_child target
Currently, no warning is displayed in Stack even if there is only one child. 
Ensure that the avoid_single_child warning is also displayed for Stack.

- [x] Unit Test

### PR DESCRIPTION
**Pull request by boywithdv**
## 🔗 Related Issues

- closes #45 

## 🙌 What's Done

- Add stack to avoid_single_child

## ✍️ What's Not Done

- 

## 🖼️ Image Differences

スクリーンショット 2024-09-03 11 43 59

## 🤼 Desired Review Method

- [x] Correction Commit
- [ ] Pair programming

> [!NOTE]
> It is possible that a reviewer's will may cause a method to be implemented that is not selected.

## Pre-launch Checklist
- [x] I have reviewed my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I updated/added relevant documentation (doc comments with ///).

### CODE REVIEW

File: packages/altive_lints/lib/src/lints/avoid_single_child.dart [hunk 1]
```diff
@@ -6,7 +6,7 @@ import 'package:custom_lint_builder/custom_lint_builder.dart';
 /// An `avoid_single_child` rule that warns against using layout
 /// widgets intended for multiple children with only one child.
 ///
-/// This includes widgets like `Column`,`Row`, `Flex`, `Wrap`,
+/// This includes widgets like `Column`,`Row`, `Flex`, `Wrap`,`Stack`
```
Comment (riscait) [inline packages/altive_lints/lib/src/lints/avoid_single_child.dart]: badge
Align comma and space conventions.
```suggestion
/// This includes widgets like `Column`, `Row`, `Stack`, `Flex`, `Wrap`
```

File: packages/altive_lints/lint_test/lints/avoid_single_child.dart [hunk 2]
```diff
@@ -36,15 +36,21 @@ class MyWidget extends StatelessWidget {
...
           children: const [
-            Text('Hello'),
+            Text('World'),
           ],
         ),
         // expect_lint: avoid_single_child
         SliverList.list(
           children: const [
-            Text('World'),
+            Text('Hello'),
```
Comment (riscait) [inline packages/altive_lints/lint_test/lints/avoid_single_child.dart]: badge
Why did you swap these two strings?
Both `Hello` looks good.

**Review by riscait — APPROVED** [review]
LGTM

File: packages/altive_lints/lint_test/lints/avoid_single_child.dart (hunk 2 above)
Comment (boywithdv) [reply packages/altive_lints/lint_test/lints/avoid_single_child.dart]: I made this change because I believe the text should be alternated, like "Hello" and "World," similar to how you would arrange them in a Column or Row. Specifically, I placed the Stack widget under the Wrap widget, so I wrote "Hello," and since the ListView widget is under the Stack, I decided "World" should be written to alternate the text.

The following commit adds a fix to make both Hello.
https://github.com/altive/altive_lints/pull/57/commits/a21c8a61cc3ef050f62eac18bf2cafad266a5dac

Comment (riscait) [reply packages/altive_lints/lint_test/lints/avoid_single_child.dart]: I see, you thought about what would happen if it appeared on the screen!
Please comment why next time.

File: packages/altive_lints/lib/src/lints/avoid_single_child.dart [hunk 3]
```diff
@@ -6,7 +6,7 @@ import 'package:custom_lint_builder/custom_lint_builder.dart';
 /// An `avoid_single_child` rule that warns against using layout
 /// widgets intended for multiple children with only one child.
 ///
-/// This includes widgets like `Column`,`Row`, `Flex`, `Wrap`,
+/// This includes widgets like `Column`, `Row`, `Stack`, `Flex`, `Wrap`
```
Comment (riscait) [inline packages/altive_lints/lib/src/lints/avoid_single_child.dart]: badge
I think I ran out of commas.
```suggestion
/// This includes widgets like `Column`, `Row`, `Stack`, `Flex`, `Wrap`,
```
